### PR TITLE
Device Groups: Disable rather than hide Device Group option

### PR DESCRIPTION
**Pull request by Pezmc**
Screenshot 2023-12-20 at 16 17 15

Easiest to review with [?w=1](https://github.com/FlowFuse/flowfuse/pull/3249/files?w=1)

Fixes https://github.com/FlowFuse/flowfuse/issues/3246

### CODE REVIEW

**Review by Steve-Mcl — APPROVED** [review]
Not blocking but this change to a component will require the docs to be updated here: https://flowfuse.github.io/forge-ui-components/#ff-tile-selection

**Comment by knolleary** [comment]
@Steve-Mcl those docs are no longer maintained since the ui-components were merged into the core repo.

**Comment by Steve-Mcl** [comment]
@knolleary I use them all the time. We discussed this recently in eng meeting. They are still up & still (mostly) relevant) so should be updated.

**Comment by Steve-Mcl** [comment]
@joepavitt please assess

**Comment by joepavitt** [comment]
> They are still up & still (mostly) relevant) so should be updated.

We don't currently have a pipeline by which to deploy those docs from within the core repo, so if we can get that working, then it's "easy", otherwise, it's going to be a painful process of needing to manually transfer over changes to the retired repo, and update the docs

**Comment by Steve-Mcl** [comment]
I will not block.  Will raise issue on the out of sync situation this PR causes.

**Pull request merged**
