### PR TITLE
Replace the AssetCompareDialog, VisibilitySelector and Logs dropdowns

### PR DESCRIPTION
**Pull request by cstns**
## Description
Replace the AssetCompareDialog, VisibilitySelector and Logs dropdowns

## Related Issue(s)

close https://github.com/FlowFuse/flowfuse/issues/4562

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by Steve-Mcl — CHANGES_REQUESTED** [review]
Nice that we can now type to get to item and esc to close etc. however there are 2 small issues:

1. The size of the dropdown does not have a min AND/OR doesnt compute a min width from entries and so colapses to an unreadable narrow list when a short item is selected
image


2. The snapshot compare list contains empty rows

image

**Review by Steve-Mcl — APPROVED** [review]
@cstns 
Functionally, I am now happy with this.

Code wise also good however I am curious about the CSS. In particular, the affect or potential impact of using such common class names like "option", "options" and "button" in the controls.  Prior to this work, they were much less likely to be impacted by any stray CSS classes as they were more verbose e.g `ff-dropdown-options`.

Feel free to tell me this is nothing to worry about and proceed.

**Comment by Steve-Mcl** [comment]
Dismissed review until dialog CSS fix is pushed

image

**Comment by cstns** [comment]
fix incoming, pending tests running locally

**Review by Steve-Mcl — APPROVED** [review]

**Pull request merged**
