### PR TITLE
Remove licensing page and redirect to pricing page

### PR DESCRIPTION
**Pull request by sumitshinde-84**
## Description

Removed the content from the licensing page and set up a redirect to the pricing page for users visiting the licensing page.

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by ZJvandeWeg — APPROVED** [review]

**Comment by ZJvandeWeg** [comment]
@sumitshinde-84 Has the redirect been tested?

**Comment by sumitshinde-84** [comment]
I haven't tested it yet; I used the same YAML used for other pages for redirection in the docs.

**Comment by ZJvandeWeg** [comment]
@sumitshinde-84 Please follow the steps in: https://github.com/FlowFuse/website?tab=readme-ov-file#running-flowfuse-documentation

**Comment by sumitshinde-84** [comment]
Done ! redirecting correctly.

**Pull request merged**
