### PR TITLE
Search applications by instances and devices

### PR DESCRIPTION
**Pull request by cstns**
## Description

Add the ability to search through an application's devices and instances

## Related Issue(s)

closes https://github.com/FlowFuse/flowfuse/issues/4157

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by cstns** [comment]
The only thing that worries me is that I had to remove the ASSOCIATIONS_LIMIT that restricted app instances/devices count in order for the search function to work on entities that are hidden by the 'x more...' tile.

**Review by Steve-Mcl — APPROVED** [review]
Very nice. 

I do have one super simple suggestion regarding UX:

When I search for something and realise there are more matching my search criteria, when I click `More` I expected my search term to be carried over.  Instead, i had to re-type my search term.

chrome_owWRavH3Tt


Carrying my search term to the next page would feel much more consistent.

Otherwise, excellent.

**Comment by Steve-Mcl** [comment]
Sorry, one more thing.

Do you have access to the ID and Type when performing the search?

I tried searching `NUC` (a type value) and `nkDqdOYgxM` (a device ID) - but the search did NOT reveal any results whereas on the next page it does.

chrome_1Fxicw5DL7

**Comment by cstns** [comment]
Thank you for the positive feedback!

> Carrying my search term to the next page would feel much more consistent.

I have to admit I did not think of that use case, there's added value in it!

> Do you have access to the ID and Type when performing the search?

Yes, the search function can be extended easily to include id search for app/instance/device.

I'll create a follow up task to include them

**Pull request merged**
