### PR TITLE
Add UI updates for Team Suspend action

### PR DESCRIPTION
**Pull request by knolleary**
Adds UI elements to support suspending a team.

### Suspend Team option added to Team Settings/Danger

image

### Confirm suspend dialog

image

### Suspended banner

Once suspended, shows banner:

image

### Reactivate team on Team Settings

image

Alternatively, setting up billing again will unsuspend the team.

### CODE REVIEW

**Comment by knolleary** [comment]
👀 ui test failures

**Review by Steve-Mcl — DISMISSED** [review]

**Comment by knolleary** [comment]
UX tests fixed and added simple ux test for basic suspend/resume cycle.

**Review by Steve-Mcl — APPROVED** [review]
approved. waiting final test finish before merge

**Comment by Steve-Mcl** [comment]
"Tests / Backend tests (18.x) (pull_request) In progress — This check has started... " taking waaaay to long.

Noticed this in the details...

```
  1) Pipelines API
       Don't overwrite fields
         keep title:
     Validation error
  Error
      at Database.<anonymous> (node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
      at /home/runner/work/flowfuse/flowfuse/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
      at new Promise (<anonymous>)
      at Query.run (node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
      at /home/runner/work/flowfuse/flowfuse/node_modules/sequelize/lib/sequelize.js:315:28
      at async SQLiteQueryInterface.insert (node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
      at async model.save (node_modules/sequelize/lib/model.js:2490:35)
      at async ProjectTemplate.create (node_modules/sequelize/lib/model.js:1362:12)
      at async TestModelFactory.createProjectTemplate (test/lib/TestModelFactory.js:115:26)
      at async Context.<anonymous> (test/unit/forge/ee/routes/api/pipeline_spec.js:2922:35)
```

**Pull request merged**
