### PR TITLE
Add "Event Scope" and "Include Children" to Instance Audit Logs

### LINKED ISSUE #4750: Project Audit Log to have include children option

### LINKED ISSUE #4751: Project audit Log users not listed
### Current Behavior

image

### Expected Behavior

should be showing a selection of users

### Steps To Reproduce

vising a project -> audit log
e.g.: https://app.flowfuse.com/instance/3ed03711-5592-4e70-9b40-b452521c394b/audit-log

### Environment

- FlowFuse version: Live FFC 2.10
- Node.js version:
- npm version:
- Platform/OS: Windows 11
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #4750
closes #4751

## Description

Adds "Event Scope" and "Include Children" to Instance Audit Logs

**NOTE** This merges into #4749. To keep #4749 manageable, we should probably not merge this in until that one is approved (but feel free to review and approve this up-front)

**NOTE2** This also inadvertently fixes #4751
image

### In action UPDATED to include associations as per discussion in #4749 comments

chrome_XA4vdFLv8z

### Tests added 

```
  Audit model
    static methods
      buildScopeClause
        for Project
          ✔ should return clause scoped for project only
          ✔ should return clause scoped for devices only
          ✔ should return clause scoped for project and all children

  3 passing (3s)
```

## Related Issue(s)

Owner: #4750
Parent: https://github.com/FlowFuse/flowfuse/issues/4684

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Will hold off reviewing until the underling branch has a PR, as I'd like to take a look at that context/basis of this branch too.

**Comment by Steve-Mcl** [comment]
> Will hold off reviewing until the underling branch has a PR.

Not sure what you mean Joe?

The base branch PR is here: https://github.com/FlowFuse/flowfuse/issues/4746

**Comment by joepavitt** [comment]
> Not sure what you mean Joe?

Ah, did go looking but didn't find it, thanks for clarifying Steve

**Comment by Steve-Mcl** [comment]
@joepavitt I've merged the changes from the base branch and applied the same edits to include the router-link in the audit log.  I've updated this PRs 1st post to reflect.

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Approved, committed some minor amendments to pluralise the labels for "Scope", but not merging as waiting on https://github.com/FlowFuse/flowfuse/pull/4749

**Pull request merged**
