### PR TITLE
Visual timeline UI

### PR DESCRIPTION
**Pull request by cstns**
## Description

Implemented the user interface described in https://github.com/FlowFuse/flowfuse/issues/4304 for the history timeline

## Related Issue(s)

part of https://github.com/FlowFuse/flowfuse/issues/4304
has to be merged in https://github.com/FlowFuse/flowfuse/pull/4647

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by cstns** [comment]
Please hold off merging the task untill the [parent pr](https://github.com/FlowFuse/flowfuse/pull/4647) is reviewd independently

**Comment by cstns** [comment]
nb: the high number of files changed is due to directory changes made to reflect the new version history hierarchy. Moved files should have no code changes

**Review by joepavitt — CHANGES_REQUESTED** [review]
UX Feedback:

- If I have the feature disabled in my Team Type, then it should default to the "Snapshots" view, not "Timeline"
- We need some better visual feedback `:hover` of the toggle between Snapshots and Timeline.

**Comment by joepavitt** [comment]
I also seem to not be seeing any auto-snapshots in the timeline? I know we discussed how busy that made it, but thought we'd agreed to keep them in?

**Comment by cstns** [comment]
> * If I have the feature disabled in my Team Type, then it should default to the "Snapshots" view, not "Timeline"

That was my main thought but settled on let's showcase the timeline even though you don't have access to it. I agree that it would be an additional step to users without access, ill change it in a bit.

> I know the timeline is vertical, but three vertical dots implies kebab menu rather than "more", so let's go horizontal please.

willdo!

> After Creating a Snapshot in the "Timeline" view, the new Snapshot doesn't display, I have to refresh, or navigate away and back and agian.

I added the load more functionality last minute and apparently messed up the loading snapshots after creation

> We need some better visual feedback :hover of the toggle between Snapshots and Timeline. Currently only have a cursor change, hover background color should be applied.

The load more functionality messed this up as well, the loading animation should have been present.

> I also seem to not be seeing any auto-snapshots in the timeline? I know we discussed how busy that made it, but thought we'd agreed to keep them in?

I didn't find a way to disable them locally so left them at that. They appear to be working fine on my end albeit I still have no idea how to disable/enable them
image

**Comment by joepavitt** [comment]
UI:

Screenshot 2024-10-21 at 14 58 27

So, newer auto-snapshots _are_ showing, the older ones are not? @Steve-Mcl - is this expected?

API Response:

Screenshot 2024-10-21 at 14 58 01

**Comment by Steve-Mcl** [comment]
> So, newer auto-snapshots _are_ showing, the older ones are not? @Steve-Mcl - is this expected?

Hard to say without seeing all data but FYI, the API returns paged results & I can see there is a `next_cursor` - perhaps its on the next page?

**Comment by cstns** [comment]
I'd like to join that call if it 's alright with you

**Comment by joepavitt** [comment]
Just local, and further pages do not contain the auto-created Snapshots. Can you verify on any instances you may have locally yourself? My throat still playing up, so trying to minimise talking.

**Comment by Steve-Mcl** [comment]
> Just local, and further pages do not contain the auto-created Snapshots. Can you verify on any instances you may have locally yourself? My throat still playing up, so trying to minimise talking.

No worries. 

I'm just finishing up a docs PR.  Will pull this and call @cstns (about 15 mins ok ?)

**Comment by Steve-Mcl** [comment]
some observations noted after pulling this branch - just getting them written up so they are not forgotten.

1. If my team does not have the visual timeline, should it not default to original snapshot view?  (a little tedious having to always switch)
   * image
2. Pictograms used are not snapshot (happy to concede this is just a copy paste of current dialog :) )
   * image
   * image

<br>

@Yndira-E
Currently, FF Cloud Production (and this PR) are using `node_catalog_red.png` for snapshots info dialogs. 
Should they be using `snapshot_red.png`?

<br>

.

**Comment by cstns** [comment]
> ...we might need something new for both the dialog and the empty state.

We only need new icons for the feature unavailable state and dialog, because users that can access the feature on any instance will always have the instance created event, so the list will never be empty.

**Comment by cstns** [comment]
> 1. If my team does not have the visual timeline, should it not default to original snapshot view?  (a little tedious having to always switch)

I added this in a later edit, this should be the case now

**Comment by Steve-Mcl** [comment]
@joepavitt 

it is unnerving how quickly we parse things out of our memory!

Spend 20 mins debugging with @cstns then something popped into my head...

From the PR: https://github.com/FlowFuse/flowfuse/pull/4509

> Enable snapshot audit logging for "auto snapshots"


We weren't capturing an audit entry prior to ...

image

In an early version of this code, I scanned the snapshots and interleaved them with the audit entries, however this was riddled with edge cases and subtleties so instead, I did what should have been done from the start - audit log the Auto Snapshots.

Moving forward, you will see all snapshots.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
