### PR TITLE
Add a directory navigation component

### PR DESCRIPTION
**Pull request by cstns**
## Description
Added a directory navigation component that resembles the provided mockup
Simplified frontend file navigation as it had too many moving parts, left the breadcrumbs object as the single source of truth

## Related Issue(s)
closes https://github.com/FlowFuse/flowfuse/issues/4449

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by cstns** [comment]
Mobile is not yet optimized

**Comment by joepavitt** [comment]
Making the `ff-text-copier` component then broke the extra gap/padding I'd added in defined on `ff-row-file`.

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Approved subjects to tests passing one final time - all looks good.

@cstns please make sure we get a changelog entry and updates in the relevant documentation

**Comment by cstns** [comment]
Created https://github.com/FlowFuse/website/issues/2565 for the changelog entry, will tackle both changelog & docs first thing tomorrow

**Pull request merged**
