### PR TITLE
3672 snapshot visibility on groups

### LINKED ISSUE #3672: Add targetSnapshot info to Device Group page
Task generated from the checklist in **Improve Snapshot lifecycle handling** [#3622](https://github.com/FlowFuse/flowfuse/issues/3622)

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

Add snapshot information to device groups as part of "Improve Snapshot lifecycle handling https://github.com/FlowFuse/flowfuse/issues/3622"

* Adds snapshot summary info to Device Group(s) API responses
* "Device Groups"
   * Adds per-row "Target Snapshot" on "Device Groups" page
   * image
* "Device Group"
   * Adds "Target Snapshot" info box in "Device Group" page
   * Adds per-row "Active Snapshot" info in "Device Group" page
   * image

#### Unit

Updates "Application Device Groups API" to check for presence of `targetSnapshot` property
```
 Application Device Groups API
    Read Device Groups
      ✔ Owner can read device groups (124ms)
```

#### e2e

A new set of e2e tests for device-groups was required to be able to check the snapshot info was present on the Device Groups and Device Group pages

```
FlowForge - Application - Device Groups
  Device Groups Overview
    ✔ can navigate to the /device-groups page with EE license
  Device Group
    ✔ can navigate to the /device-group/xxxxxxxx/devices page with EE license
    ✔ snapshot info is displayed
```

## Related Issue(s)

Closes #3672

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
You're getting an E2E test failure Steve FYI

**Comment by Steve-Mcl** [comment]
> You're getting an E2E test failure Steve FYI

Yeah, i only updated the left part of the regex (for single run test) and if failed when the full suite ran (the left hand part of the regex) 🤦‍♂️

should be better now

**Review by joepavitt — APPROVED** [review]
Works great - tested locally. Couldn't verify in staging due to https://github.com/FlowFuse/flowfuse/issues/3683.

Noticed Postgres test failure, have re-spun that.

**Comment by Steve-Mcl** [comment]
All passing now @joepavitt  - happy to merge?

**Pull request merged**
