### PR TITLE
docs: Refactor instructions for installing FlowFuse on self-hosted environment using docker

### PR DESCRIPTION
**Pull request by ppawlowski**
## Description

This pull request aims to simplify instructions for installing FlowFuse on a self-hosted environment using Docker Compose.
This pull request should be introduced together with https://github.com/FlowFuse/docker-compose/pull/160

## Related Issue(s)

closes https://github.com/FlowFuse/flowfuse/issues/4633

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by joepavitt — COMMENTED** [review]
I think there should be a reference to the Quick Start instructions at the top of this page, emphasising that this page is focussed on a production-environment. 

I'd also like to see the first iteration of a checklist here too, I'll add a scaffold checklist in place which you can then fix the content of.

**Comment by joepavitt** [comment]
Actually, the lack of checklist and "ease of navigation" is lost due to the bug in the "On this page" on our website:

Screenshot 2024-10-21 at 13 35 28

The indentation is wrong. I'll see if I can fix it quickly.

**Comment by ppawlowski** [comment]
> I think there should be a reference to the Quick Start instructions at the top of this page, emphasising that this page is focussed on a production-environment.
> 
> I'd also like to see the first iteration of a checklist here too, I'll add a scaffold checklist in place which you can then fix the content of.

Check https://github.com/FlowFuse/flowfuse/pull/4667

**Comment by joepavitt** [comment]
Not merging so you can coordinate with https://github.com/FlowFuse/flowfuse/pull/4667 and https://github.com/FlowFuse/docker-compose/pull/160

**Review by hardillb — APPROVED** [review]

**Pull request merged**
