### PR TITLE
Offboarding surveys

### PR DESCRIPTION
**Pull request by cstns**
## Description
Adds offboarding options for platform admins. 
Redirects offboarding users to a pre-defined url if set.

## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/3825

## Checklist
 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [] ~~Upgrade instructions~~
    - [ ] ~~Configuration details~~
    - [ ] ~~Concepts~~
 - [ ] ~~Changes `flowforge.yml`?~~
    - [ ] ~~Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template~~
    - [ ] ~~Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production~~

## Labels

 - [ ] ~~Includes a DB migration? -> add the `area:migration` label~~

### CODE REVIEW

**Comment by cstns** [comment]
Not sure if documentation needs updating

**Comment by cstns** [comment]
https://github.com/FlowFuse/flowfuse/issues/3849 should address an e2e test when implemented.

**Review by knolleary — APPROVED** [review]

**Comment by knolleary** [comment]
@cstns Can we disable the failing test in this branch until the linked issue is fixed when we can re-enable it?

**Comment by cstns** [comment]
I thought I did, my bad

**Comment by knolleary** [comment]
Happy for this to merge once the tests are all green.

**Pull request merged**
