### PR TITLE
Ensure consistent pictograms are used across devices and instances

### LINKED ISSUE #4450: Different pictogram on instances info popup to its empty state
### Current Behavior

image

### Expected Behavior

Like "applications" and "devices" the pictograms in the info popup should be the same as the empty state pictogram

### Steps To Reproduce

visit team with no instances
click info link in the header

### Environment

- FlowFuse version: 2.8 (live/prod)
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #4450

## Description

Use consistent choice of pictograms (as in they should match the empty state)
* use device_red.png for devices info popups
* use instance_red.png for instance info popups

## Related Issue(s)

#4450

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@Yndira-E tagging you in case you wish to double check I have used correct pictograms :)

**Comment by Yndira-E** [comment]
I think you’ve picked the right ones! 😉

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Approved, although, worth doing a check if `images/pictograms/edge_red.png"` is used anywhere, otherwise, we can delete the pictogram/file.

**Comment by Steve-Mcl** [comment]
@joepavitt a search on this branch reveals edge_red.png is no longer used.

**Pull request merged**
