### PR TITLE
Store state in local storage

### PR DESCRIPTION
**Pull request by cstns**
## Description

Adds a FE storage service.
Adds ability to configure vuex stores to fully/partially persist their state in either local or session storage.

Pre-requisite for #3999 

## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/3946
https://github.com/FlowFuse/flowfuse/issues/3917

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Any tests?

**Comment by joepavitt** [comment]
> don't see how we could add e2e tests for it

Go to page, check local storage from test, navigate away and back to it, is it still there?

**Comment by joepavitt** [comment]
@cstns the changes here have also just incorporated all of the mail SMTP stuff, and so have bloated out this PR beyond scope

**Comment by cstns** [comment]
I'll pull the smtp affair into a separate pr that points to #3973 directly.

**Comment by joepavitt** [comment]
Can I also sanity check the _why_ for this too please. I'm guessing it only really is required in SSO use cases, where users are directed _away_ from FF, so we need to maintain the redirect data for when they return?

In a full FF ecosystem, the store would persist this nonetheless?

**Comment by cstns** [comment]
It's application is for when users attempt to deploy a blueprint and don't have an account and need to follow the registration process. I haven't taken SSO into consideration because it should be transparent for users (and don't have it setup locally)

**Comment by cstns** [comment]
> In a full FF ecosystem, the store would persist this nonetheless?

It's stored in the vuex store but will be lost if the page is refreshed and not shared across tabs.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
