### PR TITLE
billing: Start billing cycle on the 1st each month

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
For billing insights and understand early in the month about where our revenue is going to end I've updated the billing cycle to start the 1st of each month. The default behaviour is to start the month the date + time they start their subscription.

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by knolleary — CHANGES_REQUESTED** [review]
`billing_cycle_anchor_config` isn't a valid parameter for the `stripe.checkout.sessions.create(..)` function we use.

According to [the docs](https://docs.stripe.com/payments/checkout/billing-cycle#create-session), we have to use `subscription_data.billing_cycle_anchor` which lacks the convenice of `billing_cucle_anchor_config` as we'll have to calculate the timestamp of the next 1st of the month ourselves.

Instead it has to be added under the existing `subscription_data` parameter (line 64) -

**Comment by ZJvandeWeg** [comment]
@knolleary I'm sorry; I don't quite now how to validate my changes. The only test I could think of was to `spy` on the map/hash constructed, which felt silly. But I don't have a great Stripe test setup. Do you know how to achieve this and validate my hacking?

**Comment by knolleary** [comment]
@ZJvandeWeg I'll take a look. I have stripe setup locally; what is harder to test is time-based events in the future where you want to check what happens at invoice time etc. That's something we have to do fairly manually.

**Comment by knolleary** [comment]
Initial test looks good. Here is what the checkout page shows:

image

Are we happy with that?

**Comment by ZJvandeWeg** [comment]
I like this a lot, thanks @knolleary !

**Review by knolleary — APPROVED** [review]

**Pull request merged**
