### PR TITLE
Replace stack tile selector with regular select on instance creation forms

### LINKED ISSUE #3895: Improve Stack selection when creating an instance

### PR DESCRIPTION
**Pull request by cstns**
## Description

Replaced the tile selector with a regular select input on instance creation forms

## Related Issue(s)

closes #3895
part of #3884

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Is it me or does it look a little out of place?

Screenshot 2024-05-30 at 16 43 55

**Comment by cstns** [comment]
I've been looking at this form for the past week, I can't really tell anymore

**Comment by joepavitt** [comment]
> I can't really tell anymore

I'm removing some margin, which helps, but also, it's rendering a `description` slow and `hasDescription` is returning `true` if the provided `template` is empty which is annoying

**Comment by cstns** [comment]
Is Empty a blueprint? the blueprint should be pre-selected and the form shouldn't reach a state where inpu.flowBlueprintId is empty or null.

**Comment by cstns** [comment]
Ahh, got it! Yes, that might have needed some touch-up now that you mentioned it

**Comment by joepavitt** [comment]
Would be great to have the NR version dropdown the same as the Application selection, but for the life of me, I can't gett the CSS to play ball

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
