### PR TITLE
add meta-information to docs

### PR DESCRIPTION
**Pull request by sumitshinde-84**
## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
@sumitshinde-84 checking this is ready to review?

**Comment by sumitshinde-84** [comment]
Not yet. I will let you know when it is ready for review.

**Comment by hardillb** [comment]
@sumitshinde-84 where are we with this please?

**Comment by hardillb** [comment]
@sumitshinde-84 How are we doing here?

Also can you resolve the merge conflicts if this is moving forwards. Thanks

**Comment by sumitshinde-84** [comment]
Oh, I forgot about this PR. I’ll get it ready today. Sorry for that!

**Comment by hardillb** [comment]
@sumitshinde-84 it looks like when you merged main into this branch it removed all the changes. Is this correct? If so we can just close it.

**Pull request closed without merging**
