### PR TITLE
Allow NR Dashboard to be loaded in iFrames

### PR DESCRIPTION
**Pull request by hardillb**
part of #4689

## Description

Allows owner to configure if Dashboards should be embeddable in an iFrame.

First pass allows dashboard to be loaded from anywhere

Has a feature test for nr-launcher of greater than 2.12.0

paired with https://github.com/FlowFuse/nr-launcher/pull/306

## Related Issue(s)

#4689

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
Tested with both DBv1 and DBv2

**Comment by hardillb** [comment]
Ready for review, but should not be merged until the nr-launcher [pr](https://github.com/FlowFuse/nr-launcher/pull/306) is merged and published (so part of 2.12.0 release)

**Review by Steve-Mcl — APPROVED** [review]
LGTM. Not merging as per request

**Comment by hardillb** [comment]
@Steve-Mcl thanks, I've tagged you on the nr-launcher side as well for completeness

**Pull request merged**
