### PR TITLE
Fix instance not being removed from the applications list after being deleted

### PR DESCRIPTION
**Pull request by cstns**
## Description

The instance was not being deleted from the applications view because it was treating the instances list as a Map.

## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/4203

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
I'm still not seeing the application disappear from the list after delete when running this branch. I note there's no reviewer for this PR, so maybe I've jumped the gun before its ready... but thought I'd let you know just in case.

**Comment by cstns** [comment]
Don't know what happened but I managed to push only a part of the fix

**Review by knolleary — APPROVED** [review]

**Comment by knolleary** [comment]
Now working - thanks @cstns

Have approved, but not merging as you hadn't explicitly asked for a review yet... so just in case you had more to come on this, I'll hold back. Otherwise, please merge.

**Comment by cstns** [comment]
This fix addresses the current issue. I still have some app view leftovers that I'll have to address but I'll do it in https://github.com/FlowFuse/flowfuse/issues/4249

I didn't know who to assign it to, thank you for the assist! I'll update and merge

**Pull request merged**
