### PR TITLE
Visualise a snapshots flows

### LINKED ISSUE #3798: Flow Viewer: Snapshots
Implement the https://github.com/FlowFuse/flow-renderer in the FF product, by adding the option to visualise any Snapshots.

Design for the modal viewer for the flows themselves available here: https://github.com/FlowFuse/flowfuse/issues/3768 although need to add the specifics of accessing/opening this from the "Snapshots" view.

- [x] #3828
    - [x] #3835 (dependant on the above)
    - [x] Add change log entry for Viewing snapshots flows
    - [ ] Update docs-user-snapshot to include a description of the view snapshot feature

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #3798 

## Description

* Adds reusable dialog `frontend/src/components/dialogs/SnapshotViewerDialog.vue`
* Adds kebab menu to `application/*/snapshots` page
  * Adds "View Snapshot" menu item to new kebab menu
* Adds "View Snapshot" menu item to existing kebab menu on `instance/*/snapshots` page
* Adds "View Snapshot" menu item to existing kebab menu on `device/*/snapshots` page

### E2E Tests

```
FlowForge - Application - Snapshots *1
    can navigate to the /snapshots page
    empty state informs users they need to add snapshots
    provides functionality to view a device snapshot
    provides functionality to view an instance snapshot

FlowForge - Instance Snapshots
    provides functionality to view a snapshot

FlowForge - Devices - With Billing
    provides functionality to view a snapshot
```

\*1: full new test file (did not previously exist)

### TODO:
- [x] e2e tests
- [ ] docs

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@joepavitt, this is mostly UI work and as such, i have requested your review.

Background: 
* It builds on the new top level snapshots API in #3833 
* Implements a shared/reusable dialog frontend/src/components/dialogs/SnapshotViewerDialog.vue
* Adds "View Snapshot" on all "snapshot" pages (e.g. can visualise both instance and device snapshots on the applications->snapshots page)

I have included e2e tests for the additions (and a couple of obviously missing extra tests - "FlowForge - Application - Snapshots" did not exist!)

**Comment by Steve-Mcl** [comment]
I am looking at the docs to see if there is somewhere we can mention this feature but an early review (considering I am OOO) would help in the case there are some issues.

**Comment by joepavitt** [comment]
> I am looking at the docs to see if there is somewhere we can mention this feature but an early review (considering I am OOO) would help in the case there are some issues.

Changelog entry for sure

**Comment by Steve-Mcl** [comment]
> > I am looking at the docs to see if there is somewhere we can mention this feature but an early review (considering I am OOO) would help in the case there are some issues.
> 
> Changelog entry for sure

Added as a task on the linked issue

**Comment by joepavitt** [comment]
As for docs, I suspect https://flowfuse.com/docs/user/snapshots/ is a sensible place

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
