### PR TITLE
Bulk Move devices UI

### LINKED ISSUE #4337: UI for Bulk Move Devices
### Acceptance Criterial

<br>

### Bulk Assigning Devices to an Application

1. Select the devices you want to assign and open the **Actions** dropdown menu adjacent to the **Add Device** button.
2. Select the **Move to Application** option and then select the application or instance you want to assign the devices to.
3. Click **Move** to continue.

Details:
* Devices that are already assigned to the chosen application will not be changed or updated.
* For any device that is moved by the operation:
   * Devices moved by the operation will have their target snapshot cleared, device group membership cleared and will be sent an update command.
   * Devices in fleet mode will automatically apply the changes resulting in devices restarting with the basic starter snapshot flows.
   * Devices in developer mode will continue to run their current flows until they are switched to fleet mode at which point they will update accordingly.

### Bulk Assigning Devices to an Instance

1. Select the devices you want to assign and open the **Actions** dropdown menu adjacent to the **Add Device** button.
2. Select the **Move to Instance** option and then select the instance you want to assign the devices to.
3. Click **Move** to continue.

Details:
* Devices that are already assigned to the chosen instance will not be changed or updated.
* For any device that is moved by the operation:
   * If the chosen instance has a target snapshot set, the newly assigned devices will inherit this.
   * If the chosen instance does not have a target snapshot set, newly assigned devices will have their target snapshot cleared.
   * Devices in fleet mode will automatically apply the changes.
   * Devices in developer mode will continue to run their current flows until they are switched to fleet mode at which point they will update accordingly.

### Bulk Removing Devices from an Application or Instance

1. Select the devices you want to remove and open the **Actions** dropdown menu adjacent to the **Add Device** button.
2. Select the **Unassign** option.
   1. Depending on where you are viewing devices, this may say "Remove from Application" or "Remove from Instance".
3. Confirm the action by clicking **Unassign**.

Details:
* Devices that are already unassigned will not be changed or updated.
* For any device that was previously assigned to an application or instance:
   * Devices in developer mode will be switched to fleet mode.
   * Devices will have their target snapshot and device group membership cleared.
   * Devices will be informed of the changes resulting in their flows being cleared and the device entering a stopped state waiting for a new assignment.

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #4337

NOTE: This PR can be reviewed and approved independently of the API PR #4336 but to keep the API PR slim and easier to review, I would recommend we merge this PR after #4336 is approved/merged.

## Description

Adds support in UI for bulk move operations
* Moves the current Bulk Delete trash icon to a dropdown
* In an instance, the dropdown displays
  * Move to Instance, Move to Application, remove from Instance
* In an Application, the dropdown displays
  * Move to Instance, Move to Application, remove from Application
* On team devices page, the dropdown displays
  * Move to Instance, Move to Application, remove from Assignment

### e2e Tests added

image

#### Team Devices Page
image

image

image

image

#### Instance Devices Page

image

image

#### Application Devices Page

image

image

## Related Issue(s)

Owner #4337
Parent #4290

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Added CSS to cover:

- 2 x Columns for the devices list when confirming actions
- Vertical alignment of the "Check All" button as it wasn't centered

**Comment by joepavitt** [comment]
Approved, but holding off merge as requested

**Comment by Steve-Mcl** [comment]
> * 2 x Columns for the devices list when confirming actions

Joe, i've added additional CSS to clean up the dlialog when names are longer in commit [088ecd2](https://github.com/FlowFuse/flowfuse/pull/4338/commits/088ecd21563b3ac18f4d8f7007ec79e2c6a96713)...

BEFORE

image



AFTER

image

**Comment by Steve-Mcl** [comment]
got the dreaded e2e bulk test error again.


```
  1) FlowForge - Devices
       bulk operations
         move
           should move selected devices to unassigned:
     TypeError: Cannot read properties of undefined (reading 'name')
      at Context.eval (webpack:///../test/e2e/frontend/cypress/tests/devices/bulk.spec.js:80:102)
```

which points to the line 
```
                        cy.get('[data-el="devices-browser"] tbody tr').contains(sacrificialDevices[0].name).parent().parent().find('.checkbox').click()
```

The weird thing here is line is part of a loop that already ran 2 out of 3 times successfully!

definitely some timing issue.


<br>

New plan. I am gonna change the tests to run be explicit as opposed to using the response data from a `wait`.

e.g.  instead of 
```
                    // wait for the devices API call to complete
                    cy.wait(['@getDevices']).then(({ response }) => {
                        const devices = response.body.devices
```

I'm gonna do 

```
                cy.wait(['@getDevices'])

                // wait for the table items to be updated
                cy.get('[data-el="devices-browser"] tbody tr').contains(deviceName1).should('exist')
                cy.get('[data-el="devices-browser"] tbody tr').contains(deviceName2).should('exist')
                cy.get('[data-el="devices-browser"] tbody tr').contains(deviceName3).should('exist')

```

**Comment by Steve-Mcl** [comment]
e2e tests update in  [fix e2e tests (again) 2db89d6](https://github.com/FlowFuse/flowfuse/pull/4338/commits/2db89d6784dd50a71a0d7a10c64f5aba2d210dfc) 

NOTE: I ran this locally at least 20 times without issue.  4th time _should_ be the charm.

_defo a cypress skill issue_

**Pull request merged**
