### PR TITLE
auto genrate license and display

### PR DESCRIPTION
**Pull request by sumitshinde-84**
## Description

This pull request automates the generation and display of licenses for requesters. It integrates with our existing Node-RED application (sales flows) to handle license generation. The PR initiates a POST request to an API endpoint within the Node-RED instance. This endpoint generates the license and returns it in the response. Following this, it triggers further flows to store the information in context storage, display it on the dashboard, and log it on Google Sheets.

After the requesting license, requester can see it as following 

WhatsApp Image 2024-07-05 at 5 50 27 PM (1)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
Thanks, @joepavitt, for the suggestion! Yes, it is necessary to add that note; I will update it.

**Comment by ZJvandeWeg** [comment]
Approved from my side, @joepavitt can you do the honours with review?

**Comment by joepavitt** [comment]
, waiting on https://github.com/FlowFuse/flowfuse/pull/4105#issuecomment-2209215694 to be actioned first

**Comment by sumitshinde-84** [comment]
hi @joepavitt , I have updated the Pr to include the note and made some improvement in license block

**Comment by joepavitt** [comment]
There is still a sentence there after the code block saying "your license will be sent yo you within the next business day" - we don't need that anymore.

I'd also move the `<strong />` content into it's own paragraph too to make sure it catches users' eyes

**Comment by sumitshinde-84** [comment]
> There is still a sentence there after the code block saying "your license will be sent yo you within the next business day" - we don't need that anymore.
> 
> I'd also move the `<strong />` content into it's own paragraph too to make sure it catches users' eyes

Yes, that sentence refers to the HubSpot form submit response. I'm not sure how to remove it; I think this should be done within HubSpot. Furthermore, I have moved the strong content into its own paragraph.

**Review by joepavitt — APPROVED** [review]

**Comment by sumitshinde-84** [comment]
@joepavitt i have made an update to this PR, now it will not show the HS thank you message.

**Pull request merged**
