### PR TITLE
Add ability to push any snapshot to application owned device

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

* Presents a "Deploy Snapshot" button to list of snapshots under an application owned device

### Finer details.

* An instance OR device owned snapshot can be set as the target for an application device. This is possible via the device -> snapshots tab
* Taking a snapshot of a device now supports "[x] Set As Target" - this was required since switching out of DEV mode would cause the app owned device to reload current starter flows
   * Therefore the "Device" -> "Overview" now shots target and active snapshot for App owned devices.
* When a snapshot is created, deleted, assigned, an Application Audit log entry is made.
* No new APIs were created for this.

### TODO: 

* [x] audit log entries and formatting
* [x] tests
* [x] docs

## Proposed verification procedures

verify criteria

For stacks 3.0.x and 3.1.x

1. Run new FF app with older device agent
   - Device owned by application
      - [ ] DevMode: Device Editor works
      - [ ] DevMode: Snapshot from device works
   - Device owned by instance
      - [ ] DevMode: Device Editor works
      - [ ] DevMode: Snapshot from device works
      - [ ] Setting target snapshot works

2. Run old FF app with new device agent
   - Device owned by application
      - [ ] DevMode: Device Editor works
   - Device owned by instance
      - [ ] DevMode: Device Editor works
      - [ ] DevMode: Snapshot from device works
      - [ ] Setting target snapshot works

3. Running all new code
   - Device owned by application
      - [ ] DevMode: Device Editor works
      - [ ] DevMode: Cannot deploy any snapshot
      - [ ] DevMode: Snapshot from device works
          - [ ] DevMode: Creating a snapshot with Set As Target updates the "Target Snapshot" (check overview screen)
          - [ ] !DevMode: Switching off DevMode causes the new target to be applied (device restarts with new FF_SNAPSHOT_ID etc)
      - [ ] !DevMode: Deploy Own snapshot works 
          - [ ] DevMode: Device Editor works
          - [ ] DevMode: Snapshot from device works
      - [ ] !DevMode: Deploy Instance snapshot works 
          - [ ] DevMode: Device Editor works
          - [ ] DevMode: Snapshot from device works
      - [ ] Remove device from application then add device to instance
  
   - Device owned by instance
      - [ ] DevMode: Device Editor works
      - [ ] DevMode: Snapshot from device works
      - [ ] Setting target snapshot works
      - [ ] Remove device from instance then add device to application

4. Application Audit logs are generated (with icons and subtext) for
    - [ ] Device Target Snapshot Set
    - [ ] Device Snapshot Created
    - [ ] Device Snapshot Deleted
 
5.  Docs 
    - [ ] updated

## Related Issue(s)

#2484

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@joepavitt - I have requested you for review of vue / frontend / audit log stuff

@knolleary everything else.

It it worth me doing a demonstration video to aid your understanding of this?

**Comment by knolleary** [comment]
Have pulled this down and will give it a run through.

One bit that stood out:

image

'Device owner' - I don't think we use 'ownership' type terminology elsewhere (unless I've missed it). Given the action is 'Assign', could/should this column be 'Assigned to'

/cc @joepavitt

**Comment by knolleary** [comment]
Just push a small UX fix for the target/actual snapshot info on the Device Overview page. The Target Snapshot was stacking the icon with the label:

image

Have make it match the layout of the Active row.

**Comment by joepavitt** [comment]
> Just push a small UX fix for the target/actual snapshot info on the Device Overview page. The Target Snapshot was stacking the icon with the label:

Thought I'd already fixed that last week, apologies.

**Comment by joepavitt** [comment]
> 'Device owner' 

I agree with the "Assigned To" terminology

**Review by knolleary — APPROVED** [review]

**Comment by Steve-Mcl** [comment]
> I agree with the "Assigned To" terminology

@joepavitt , after discussion with Nick and the amount of testing, we have pressed ahead.  I will raise a size 1 task around consistent "Assigned To" in the UI as a follow up.

**Pull request merged**
