### PR TITLE
Stop polling a device if it's deleted

### PR DESCRIPTION
**Pull request by hardillb**
fixes https://github.com/FlowFuse/flowfuse/issues/3712

## Description
Stop polling for device status if it gets a 404 HTTP status code which implies that the device has been deleted.

## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/3712

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
@joepavitt can you have a look at this please, I'd like to get it merged

**Comment by joepavitt** [comment]
@Steve-Mcl in reviewing this PR I noticed that the "last seen" status refreshed every 5 seconds when on the Overview page, but not the others. Can see [this](https://github.com/FlowFuse/flowfuse/blob/10c670e8093a71803b2ad91e48c7873d6ce0aefa/frontend/src/pages/device/index.vue#L300) was added in by you a month ago to protect the Settings page, but is there a reason why it's not also running on Snapshots, Audit Log, Device Logs pages?

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl in reviewing this PR I noticed that the "last seen" status refreshed every 5 seconds when on the Overview page, but not the others. Can see [this](https://github.com/FlowFuse/flowfuse/blob/10c670e8093a71803b2ad91e48c7873d6ce0aefa/frontend/src/pages/device/index.vue#L300) was added in by you a month ago to protect the Settings page, but is there a reason why it's not also running on Snapshots, Audit Log, Device Logs pages?

It is a bit more than that Joe.

It refreshes "always" on pages without user input or long lists (i.e. overview AND developer pages)
It refreshes on ALL pages if the state unknown or is intermediate.

```
            // Only refresh device via the timer if we are on the overview page, developer mode page
            // the device status is empty or the device is in a transition state
            // This is to prevent settings pages from refreshing the device state while modifying settings
            // See `watch: { device: { handler () ...  in pages/device/Settings/General.vue for why that happens
            const settingsPages = ['DeviceOverview', 'DeviceDeveloperMode']
            try {
                if (settingsPages.includes(this.$route.name)) {
                    await this.loadDevice()
                } else if (typeof this.device?.status === 'undefined') {
                    await this.loadDevice()
                } else if (deviceTransitionStates.includes(this.device?.status)) {
                    await this.loadDevice()
                }
```


This was necessary as prior to this, status was not being updated on certain pages and this was a quick win to (better) show actual state.

the better/harder/longer/slower solution was to re-engineer the pages with inputs and their own polling to use a store/vuex

**Comment by joepavitt** [comment]
> It refreshes "always" on pages without user input or long lists (i.e. overview AND developer pages)

It doesn't refresh on Snapshots, or Audit Log or Device Logs though, and that's annoying... I'll raise this as a separate issue because it's not linked (as I thought it might have been) to Ben's PR.

**Review by joepavitt — APPROVED** [review]

**Comment by Steve-Mcl** [comment]
> It doesn't refresh on Snapshots, or Audit Log or Device Logs though

And that was true prior to the code you linked. What that code did was actually allow status to be updated when on those other pages when state was unknown or undetermined. 

Prior to the linked code, polling only occurred on overview and only until it reached a non indeterminate state. 

As I said, it was a quick win improvement. The better solution is ...

**Pull request merged**
