### PR TITLE
Better device proxy cache

### PR DESCRIPTION
**Pull request by hardillb**
part of #3414 
## Description

Rather than requesting the 4 largest files from the device agent every time the device editor is loaded it will load them from a local instance on @node-red/editor-client of the matching version if present.

Still need to work out how to install the right versions of @node-red/editor

## Related Issue(s)

#3414

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [x] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
@Steve-Mcl the default path for a localfs test is `var/device/cache` 

And `@node-red/editor-client` needs to be installed under that in the matching Node-RED version number (like stacks)

e.g. in `var/device/cache` create `4.0.5` and run `npm install @node-red/editor@4.0.5` --prefix 4.0.5`

Also needs the head of device agent to work

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl the default path for a localfs test is `var/device/cache` in the flowfuse directory (same place as `var/stacks` and `var/projects` for localfs)
> 
> And `@node-red/editor-client` needs to be installed under that in the matching Node-RED version number (like stacks)
> 
> e.g. in `var/device/cache` create `4.0.5` and run `npm install @node-red/editor-client@4.0.5` --prefix 4.0.5`
> 
> Also needs the head of device agent to work

Thanks Ben. First job for me this morning will be to pull and test this locally.

**Comment by hardillb** [comment]
@Steve-Mcl done (this will probably break the pre-staging env)

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl done (this will probably break the pre-staging env)

@Pezmc is it possible to delete / refresh the pre-staging for this?

@hardillb will this affect staging?

**Comment by hardillb** [comment]
@Steve-Mcl we have already deleted the pre-staging env, we did not recreate it. It can't be tested on pre-staging as there is no broker for the device comms needed to enable device editor mode.

At the moment we are not deploying the @node-red/editor-client packages in the containers so this will run as "normal" and not use the cached copies. The update to the containers will get done later.

**Review by Steve-Mcl — APPROVED** [review]
As discussed in slack, I added the try-catch and fall through to original tunneling logic.

This works fantastically well Ben I gotta say, its like night & day!

For the record, I added temporary logging to ensure things were working as expected, here are the results:

```
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\red\style.min.css
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\vendor.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\red\red.min.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\monaco\dist\editor.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\red\style.min.css
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\vendor.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\red\red.min.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\monaco\dist\editor.js
[2024-12-18T12:20:59.777Z] INFO: Device 36LO0L3Odb tunnel id:1 - new editor connection req:54 
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\mermaid\mermaid.min.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\monaco\dist\css.worker.js
Serving cached file: C:\Users\xxx\repos\github\flowfuse\dev-env\packages\flowfuse\var\device\cache\4.0.7\node_modules\@node-red\editor-client\public\vendor\monaco\dist\ts.worker.js
```

**Pull request merged**
