### PR TITLE
Add e2e tests

### PR DESCRIPTION
**Pull request by cstns**
## Description

add leftover e2e tests

## Related Issue(s)

#3646

### CODE REVIEW

**Comment by joepavitt** [comment]
@Steve-Mcl the test failing here is the same one that you're seeing too, right?

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl the test failing here is the same one that you're seeing too, right?

Correct: 

```
  1) FlowForge - Team Overview (Home) - With License
       shows a list of cloud hosted instances:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-action="open-editor"]`, but never found it.
      at Context.eval (webpack:///../test/e2e/frontend/cypress/tests-ee/team/overview.spec.js:126:62)
```

And the changes I made to eradicate `:contains` seems to have not fixed it (though the error is clearer now)

[link](https://github.com/FlowFuse/flowfuse/actions/runs/8813719516/job/24192072615?pr=3766#step:7:496)

```
  1) FlowForge - Team Overview (Home) - With License
       shows a list of cloud hosted instances:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'application-device-a' within the element: <li> but never did.
      at Context.eval (webpack:///../test/e2e/frontend/cypress/tests-ee/team/overview.spec.js:123:27)
```


for reference, this is the changes I made: https://github.com/FlowFuse/flowfuse/pull/3766/files#diff-634c66e038264ac5c548b546751838ea8a809cea4dc9f92729f175fbc510eeaeR1-R135


NOTE: These tests all pass locally.  Something odd is going on!

**Comment by cstns** [comment]
on it

**Comment by cstns** [comment]
Fixed the first failing test that @Steve-Mcl mentioned but didn't encounter the 2nd locally or remotely on GH. No package updates after npm install and no changes afterwards, only a browserlist warning.

also fixed some linting errors which were my own doing

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
