### PR TITLE
Make link a button so it's obvious for change team type

### LINKED ISSUE #2904: Link to change team type hidden
### Current Behavior

The "here" is a link, but the styling makes it near impossible to find

image

### Expected Behavior

A big blue button rather than a hidden link

### Steps To Reproduce

Team -> Settings -> Edit team settings

### Environment

- FlowForge version: 1.12.3
- Node.js version: NA
- npm version: NA
- Platform/OS: NA
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by hardillb**
fixes #2904

## Description

The link to change the team type was impossible to find in the team settings (light grey with no highlighting in the sentence)

Changed it to a secondary button so it's clearer what the intention is.

## Related Issue(s)

#2904

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
Can you include a screenshot of the result to show the difference?

**Comment by hardillb** [comment]
image

**Comment by hardillb** [comment]
before:

original

**Review by Pezmc — APPROVED** [review]

**Comment by joepavitt** [comment]
Not really a fan of the button just randomly sitting between the label and value. Can you make the value/button inline please?

`class="flex justify-between"` should do the job on a parent of the value and button.

**Comment by hardillb** [comment]
Talked to Joe, couldn't make the layout work with current page design, but button is better than the hidden link, new task issue raised to look at page:

https://github.com/FlowFuse/flowfuse/issues/3241

**Pull request merged**
