### PR TITLE
Draft Pull Request: Added SSO/SAML group mapping options

### PR DESCRIPTION
**Pull request by johnebgood**
## Description
Draft PR for feedback.

Testing changes and requesting feedback for features to map SAML groups to teams, admin and user logins. Also the ability to default the login page to SSO provider and auto create users on initial sucessful login attempt from the SSO provider. This is my 2nd PR ever so apologies for my ignorance on coding and git best practices. If anyone could provide guidance on anything I should adjust in code, naming conventions etc. I would very much appreciate it.

Additions:

SSO Provider Settings additional fields:
image

Team Settings additional fields:
image

Added DB columns:

    // These were added but then realized that I was storing the values on the options field and they're not used. 😄 
    await context.addColumn("SAMLProviders", "allowAllSSO")
    await context.addColumn("SAMLProviders", "samlUserGroup")
    await context.addColumn("SAMLProviders", "samlAdminGroup")
    await context.addColumn("SAMLProviders", "defaultLogin")
    await context.addColumn("SAMLProviders", "autoCreateUser")

    // Added to pass SAML groups on the user object from ee/routes/sso/auth.js to Session.js
    await context.addColumn('Users', 'saml_groups')

    // Team group mappings
    await context.addColumn("Teams", "samlGroupOwner")
    await context.addColumn("Teams", "samlGroupMember")
    await context.addColumn("Teams", "samlGroupViewer")
    await context.addColumn("Teams", "samlGroupDashboard")

    // Added to track if a user was added to a team with SAML mapping. On SSO login all SAML mapped teams are removed 
    // and added fresh from the list of returned groups. This will allow for non-SAML mappings of teams that will persist.
    addColumn("TeamMembers", "samlAdded")
          
## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/2832
https://github.com/FlowFuse/flowfuse/issues/2919

## Checklist

 - [ ] Suitable unit/system level tests have been added and they pass 
   I have no idea how to make unit tests
 - [x] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
Thanks for the PR @johnebgood  - I was hoping to join one of your Twitch live streams this week, but timezones didn't work in my favour :)

This PR is covering a lot of ground and a number of different items from our backlog, so it may take some time for us to work through all the details. We hadn't done any design work on our side yet for any of this, so we need to do some catch-up to properly understand what is being proposed here.

Part of that is better understanding on our part how SAML groups can be managed across the different SAML providers we already have customer using.

A large part of it is the UX of how any such mappings are configured. We have to keep in mind how this all appears to our FF Cloud platform users. Your screenshots show some level of configuration is needed in the individual Teams. I'm not sure that is suitable for how we manage our FF Cloud platform; most users aren't SSO enabled and presenting all of these options to them in their teams would be confusing.

I'll have a play with your PR over the next few days and see where we get to.

**Comment by johnebgood** [comment]
Thanks for the feedback @knolleary, I completely understand that the way I did it is probably not suitable for all SSO providers or for release in the current state, I mainly wanted to hack in some features and get to know how the application works and test out some possibilities to communicate what I would like to see for the end result. The issue thread is probably not the best place for me to be hashing out what I'm working on either. I'm going to keep this draft PR open as I make adjustments and move stuff around, I would appreciate any feedback as I've been out of web development for 18 years. 😅

**Comment by knolleary** [comment]
Hi @johnebgood 

Wanted to update you on what we've been doing in this space.

With the 2.0 release tomorrow we are introducing the ability to manage team membership via SAML groups. We've taken an approach that is somewhat different to yours, but is more suited to the FF Cloud use cases we have.


You can see the details in the PR: https://github.com/FlowFuse/flowfuse/pull/3291

To summarise the approach:

 - An SSO Configuration has a new option to enable team membership management
 - If enabled, it can be applied to the whole platform, or to select teams.
 - If 'selected teams' is chosen, the admin provides a list of the teams that are 'in scope' of the membership management

We then rely on a naming convention of the groups: `ff-<team slug>-<role>`.

This relies on the Identity Provider giving us the group names. I appreciate Microsoft Entra provides ids by default, but it can be configured to return the group names instead. This avoids the need to manage id/mappings on the platform side.

This does not cover:
 - user provisioning - we still require a user to be created on the platform first
 - managing admins - it almost got included, but was beyond what was needed for the immediate customer requirement so I pushed it back

Would be interested to hear your feedback on this.

**Comment by hardillb** [comment]
@johnebgood I'm going to close this as we have now delivered our SAML approach and we are not going to merge this and it is getting more and more out of sync with the current main branch.

Thanks again for sharing this.

**Pull request closed without merging**
