### PR TITLE
Fix snapshot package.json download dependencies

### LINKED ISSUE #4288: Dowloaded package.json for instance snapshot missing dependencies
### Current Behavior

`dependencies` section of package.json downloaded from the instance snapshot list is empty

### Expected Behavior

This should list the installed nodes

### Steps To Reproduce

Create instance, install nodes, take snapshot, download package.json

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by hardillb**
fixes #4288

## Description

The code had an extra `settings` that does not appear to be present in the snapshot summary.

## Related Issue(s)

#4288

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
Just checking the device code as well

**Comment by Steve-Mcl** [comment]
Ben unfortunately, not working for application -> snapshots.

#### downloading package from instance -> snapshots
```
{
  "name": "real-grey-partridge-3387",
  "description": "instance snapshot, new snap - ",
  "private": true,
  "version": "0.0.0-3rzOoXEDlL",
  "dependencies": {
    "node-red": "3.1.11",
    "@flowfuse/node-red-dashboard": "1.5.1",
    "node-red-contrib-cron-plus": "2.1.0",
    "node-red-contrib-mssql-plus": "0.12.2",
    "node-red-contrib-postgresql": "0.14.0",
    "@flowfuse/nr-project-nodes": "0.7.0",
    "@flowfuse/nr-file-nodes": "0.0.5"
  }
}
```

#### downloading SAME package from application -> snapshots
```
{
  "name": "real-grey-partridge-3387",
  "description": "instance snapshot, new snap - ",
  "private": true,
  "version": "0.0.0-3rzOoXEDlL",
  "dependencies": {}
}
```


<br>

Also, as this is a regression it should have tests (sorry - cypress is no-ones best friend so I have prepared an example that should take you like 90% of the way)

Below is an example of cypress reading the downloaded snapshot and checking some stuff but you will need to do this in the 3 places snapshot downloads are done...

* test/e2e/frontend/cypress/tests-ee/devices/snapshots.spec.js
* test/e2e/frontend/cypress/tests/instances/snapshots.spec.js
* test/e2e/frontend/cypress/tests/applications/snapshots.spec.js

```
    it('download snapshot package.json', () => {
        cy.intercept('GET', '/api/*/projects/*/snapshots', deviceSnapshots).as('snapshotData')
        cy.intercept('GET', '/api/*/snapshots/*').as('snapshot')

        // ensure package.json does not exist in the downloads folder before the test
        cy.task('clearDownloads')
        // click kebab menu in row 1
        cy.get('[data-el="snapshots"] tbody').find('.ff-kebab-menu').eq(0).click()
        // click the Download Package.json option
        cy.get('[data-el="snapshots"] tbody .ff-kebab-menu .ff-kebab-options').find('.ff-list-item').eq(IDX_DOWNLOAD_PACKAGE).click()

        cy.wait('@snapshot').then(async interception => {
            // At this point, the endpoint has returned but occasionally, the test fails as the file is not yet written to the filesystem.
            // To counter this, there is a short 250ms wait to allow time for the file to be written to the filesystem.
            // A better solution would be to use a cy.command (named waitForFileDownload) that polls the downloads folder
            // and calls `cy.wait` with timeout and retry. This would allow the test to wait for the file in a more reliable way.
            // For now, a small delay here gets the job done.
            cy.wait(250) // eslint-disable-line cypress/no-unnecessary-waiting
            const downloadsFolder = Cypress.config('downloadsFolder')
            return cy.readFile(`${downloadsFolder}/package.json`)
        }).then((packageObject) => {
            expect(packageObject).to.have.property('name', 'instance-2')
            expect(packageObject).to.have.property('description')
            expect(packageObject).to.have.property('dependencies')
            expect(packageObject.dependencies).to.have.property('node-red', '4.0.0')
            expect(packageObject.dependencies).to.have.property('@flowfuse/nr-project-nodes', '0.6.4')
            expect(packageObject.dependencies).to.have.property('@flowfuse/node-red-dashboard', '*')
        })
    })
```

**Comment by hardillb** [comment]
@Steve-Mcl Tests added (The application test is a bit thin since none of the snapshots have any dependencies because they are all against a instance that is never started.)

**Review by Steve-Mcl — APPROVED** [review]

**Comment by Steve-Mcl** [comment]
> The application test is a bit thin since none of the snapshots have any dependencies

Thats ok, behind the scenes if one works, the other works :)

**Pull request merged**
