### PR TITLE
Add credentialSecret to snapshot model and update logic to use it

### LINKED ISSUE #3644: Migrate credentialSecret into Snapshot model
Part of #3622 

Task is to add credentialSecret to the ProjectSnapshots table so we are not reliant on the originating instance/device existing in order to access the snapshot.

The open question is whether the db migration should populate this column for all existing snapshots. We *could* choose to only populate for new snapshots; the logic to retrieve the credentialSecret could fall back to existing behaviour if not set on the snapshot. This would mean existing snapshots are still vulnerable to being orphaned, but the risk would be diminishing as applications tend to move forwards.

Will need to evaluate the cost/risk of doing full migration.

```[tasklist]
### Tasks
- [x] Add column to ProjectSnapshots table
- [x] Update snapshot creation logic to populate credentialSecret column
- [x] Update logic that retrieves the credentialSecret to look in the new place
```

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #3644 

## Description

This adds `credentialSecret` to the snapshot model so we no longer depend on the parent of the snapshot existing. This makes it easier to reason about the snapshots as they get moved around.

The db migration will populate the new column with the appropriate value from with the Device or ProjectSettings tables. I've tested this migration in both sqlite and postgres.

I have looked at many of the pipeline tests that relate to snapshots. They checked the result had a credentials property, but didn't try to validate the value. I've updated the tests in a few places to validate the credentials are properly encrypted with the expected key.

I've also done various bits of manual testing with rollbacks, instance-assigned devices, app-assigned devices, pipeline deploys to instances and devices/device groups.

### CODE REVIEW

**Comment by knolleary** [comment]
Am going to spin up a test env to do some more pointing and clicking before we merge, but please continue the review of the code.

**Comment by knolleary** [comment]
Hitting a postgres-only test failure. Can recreate locally on pg, but on sqlite. Investigating...

**Comment by knolleary** [comment]
Test fixed.

**Comment by Steve-Mcl** [comment]
code and tests read fine but i am pulling this branch for a quick run through.

**Review by Steve-Mcl — APPROVED** [review]
code review and local testing with app device and other instance snapshot deploys 👍

**Comment by Steve-Mcl** [comment]
@knolleary Approved.  Had to update branch and so tests are re-running. Merge when tests pass.

**Comment by Steve-Mcl** [comment]
@knolleary now that #3645 is merged, we can merge this. 

_#3645 had migration "20240325-01-add-teamTypeScope-to-FlowTemplates.js" which has a date 2 days prior to this PR "20240327-01-add-credentialSecret-to-snapshots.js"_

I've merged main to this and will merge as soon as tests pass unless you should up

**Comment by knolleary** [comment]
@Steve-Mcl all good - thanks

**Pull request merged**
