### PR TITLE
Instance Protection 

### PR DESCRIPTION
**Pull request by hardillb**
fixes https://github.com/FlowFuse/flowfuse/issues/3488
## Description

Adds the concept of Protected Instances.

- These can only be deployed to via a pipeline and then only by the Team Owner.
- Access to the Node-RED Editor is read only for all Team memebers including the Owner.

## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/3488

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Instruction to enable this:

 - Team Types > Select Team > Features > Toggle ON "Protected Instances"

**Comment by joepavitt** [comment]
We would benefit from Cypress tests here too, sorry to be the pain...

**Review by joepavitt — CHANGES_REQUESTED** [review]
Functionally, seems to do the job fine, I have a few pain points around disabling of elements without feedback to the user on _why_ that's happening, but will open a separate issue for that, as that's an app-wide problem, not just here.

We are missing Cypress tests though, which should be added to the `pipelines.spec.js` test suite at least. These things csan be fragile, and given it's permissions related, want to make sure it's stable.

**Review by Steve-Mcl — CHANGES_REQUESTED** [review]
As discussed on Slack: If the editor has been opened previously, then you switch on the protection & relaunch the editor, you still have write access to the flows.  

Additionally, the Pr has no docs update - are the docs update in a separate PR or is there a follow up issue/task?

**Comment by hardillb** [comment]
@joepavitt I've started on some cypress tests, but this is going to be a pain, it needs to run things as 2 separate users

1. Team Owner to set the protected mode
2. Team Member to not be allowed to run the pipeline

**Comment by joepavitt** [comment]
We have the cy.login command wrapper, possibly even a cy.logout wrapper too? 

The login wrapper atm I think runs in the "beforeAll" script for each test suite.

Perfectly plausible to do what you need, just can't remember what's in place already. Will confirm at desk tomorrow

**Comment by joepavitt** [comment]
Checkout: https://github.com/FlowFuse/flowfuse/blob/main/test%2Fe2e%2Ffrontend%2Fcypress%2Fsupport%2Fcommands.js

That details the commands we've added to help

**Comment by hardillb** [comment]
OK, got a mostly working test, just don't know how to check for the disabled play button on the stage.

**Comment by Steve-Mcl** [comment]
> just don't know how to check for the disabled play button on the stage

It may depend on the button type but other parts of the 3e3 tests use `cy.get('button.ff-btn.ff-btn--danger').should('be.disabled')`

**Comment by hardillb** [comment]
@Steve-Mcl It should now log out any active NR instance (only to be discovered on a deploy) and there is some "docs"...

@joepavitt Might need 5mins with you tomorrow to add a little bit more to the Cypress tests

**Comment by joepavitt** [comment]
`should('be.disabled')` is the line you're looking for to check a button cannot be clicked.

**Comment by Steve-Mcl** [comment]
> > just don't know how to check for the disabled play button on the stage
> 
> It may depend on the button type but other parts of the e2e tests use `cy.get('some-selector').should('be.disabled')`

Did this help Ben?

Is this ready for review now or is there more tests you wish to get in first?

**Review by joepavitt — APPROVED** [review]

**Review by Steve-Mcl — COMMENTED** [review]
@hardillb in testing, I disabled the "Protected Instances" option in team types and the protection remains on for those instances that were set protected. The badge remains visible and the protection is still in place (flows cannot be edited).  While I would not call it not a bug (more a side-effect of me leaving instances in protected mode when disabling the capability), should we not also actually disable the feature (i.e. permit editor access / permit pipeline deploys / hide the "protected" badge)?

Happy to approve as is but perhaps a follow up task should be added?

This may be more for @MarianRaphael to answer?

**Comment by Steve-Mcl** [comment]
> as we are not likely to enable then immediate disabled this feature

we "no", people, "likely"

Will approve and merge having raised the point for consideration.

@MarianRaphael please consider this point about disabling the option

**Review by Steve-Mcl — APPROVED** [review]

**Pull request merged**
