### PR TITLE
DevOps Pipeline: Block attempted deploys to devices in developer mode

### LINKED ISSUE #3112: Prevent deploys to devices in development mode
### Description

Today; it's possible to deploy to a device that's currently in developer mode, this deploy will never complete until the device is taken out of developer mode.

1. It should be clear from the dev-ops pipeline that the device is in developer mode
2. Deploy should fail with a clear error if the device is in developer mode

Screenshot 2023-11-23 at 10 37 18

Follow up to #2756

### Epic/Story

_No response_

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

- Prevents deploys from being started if the target device is in developer mode to prevent confusing UX. The deploy would never finish as the device will not pull in the new target snapshot in this mode.
- Updates the pipelines UI to make it clear when device is in developer mode
- Adds happy bath UI coverage of stage creation with devices and device deploys

Screenshot 2023-12-04 at 11 01 39

---

~Draft for UI/UX review from @Yndira-FlowForge  or @joepavitt~

~Prevents deploys from being started if the target device is in developer mode to prevent confusing UX. The deploy will never finish as the device will not pull in the new target snapshot in this mode.~

~Also adds the developer mode icon to the pipeline stages view. Thoughts?~

Screenshot 2023-11-24 at 17 25 35
Screenshot 2023-11-24 at 17 59 59
Screenshot 2023-11-24 at 18 00 07

## Related Issue(s)

Fixes #3112 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
> A developer mode icon, displayed to the right, only when the device is in that mode.

@Yndira-FlowForge we already have developer mode icon, which is the purple beaker that @Pezmc has introduced here.

**Comment by Yndira-FlowForge** [comment]
@joepavitt interesting... When you enable/disable the dev mode, you have to use this toggle:
Screenshot 2023-11-28 at 12 06 05

That's where I got the icon from, and now I see what you mean in a list of devices... 

However, that purple beaker icon is in a [prototype](https://private-user-images.githubusercontent.com/73583313/277613125-cc56de9a-5f4e-461a-b3d5-77a6798bb3ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzAxMDIsIm5iZiI6MTcwMTE2OTgwMiwicGF0aCI6Ii83MzU4MzMxMy8yNzc2MTMxMjUtY2M1NmRlOWEtNWY0ZS00NjFhLWIzZDUtNzdhNjc5OGJiM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZWIyZjc3YjY1OTVlODRhZGY2OWYxNDFlZWM4YzI4OGEyNDZjYzEzZDMzMzExZmI2ZWZiYjljZTZkNTE4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZSki4nb2EMzmjY2mybH5D356YP2pDnQOjeqgwwgQEc) for the blueprints library for data analytics

Screenshot 2023-11-28 at 12 10 55

It's slightly different, but that's why I suggested keeping the device icon... I thought it could be confused with the future blueprints visual code.

I'm just mentioning in case you'd like to make some adjustment there.

**Comment by joepavitt** [comment]
All very valid points @Yndira-FlowForge - we should look at consistency with the icon. I think the `</>` icon on it's own looks a little lost, but we could wrap it in an `o` to make it more obvious as an _icon_ when used outside of the toggle?

The beaker is a nicer, solid icon, but doesn't immediately shout "dev mode" when looking at it.

**Comment by Yndira-FlowForge** [comment]
To make it more obvious that the pipeline is blocked, I added the "forbidden" icon, but not sure where it would work better:
- Covering the "play" icon
- Or covering the chevron

And, I was just playing with the dev icon. If it has to stand out I'd suggest a filled icon, but this is supposed to be a temporary state, and that makes me think it should be outlined...

Screenshot 2023-11-28 at 12 42 19

Screenshot 2023-11-28 at 12 35 21

**Comment by joepavitt** [comment]
Toying with making it stand out even more for the specific stage in question:

Screenshot 2023-11-28 at 13 21 13

Screenshot 2023-11-28 at 13 21 19

Purple is inline with existing theme of "Dev Mode", but don't think it draws enough attention here, so also tried the red variant

**Comment by Yndira-FlowForge** [comment]
@joepavitt I think that's great! Red variant is the winner for me.

**Comment by joepavitt** [comment]
@Pezmc okay to cover these changes, or want me to handle dev work?

**Comment by Pezmc** [comment]
If you have the cycles you doing it would be great @joepavitt!

**Comment by Pezmc** [comment]
@joepavitt We don't currently have that. It's based on the StorageFlows table, which we don't have for devices unfortunately. There _might_ be somewhere we can calculate something similar for devices.

**Review by hardillb — APPROVED** [review]

**Pull request merged**
