### PR TITLE
Add Instance log passthrough support

### PR DESCRIPTION
**Pull request by hardillb**
part of #3324

## Description

Allow nr-launcher to print Node-RED logs (in JSON format) to stdout. This allows it to be ingested by log services on docker/k8s

## Related Issue(s)

#3324 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
Pairs with https://github.com/FlowFuse/nr-launcher/pull/207

**Comment by knolleary** [comment]
My concern is what a FF Cloud user will think this option does - as it will do nothing for them. And there needs to be some documentation somewhere on what this feature does.

Does this really need to be on a per-instance basis or can it be an option set via the yml file?

**Comment by hardillb** [comment]
It could be done as a env var injected into the container by the driver. I'll give it a rework

**Comment by hardillb** [comment]
Move to driver level configuration

https://github.com/FlowFuse/driver-k8s/pull/136
https://github.com/FlowFuse/driver-docker/pull/82
https://github.com/FlowFuse/driver-localfs/pull/114

https://github.com/FlowFuse/helm/pull/300

**Pull request closed without merging**
