### PR TITLE
Bill of Materials - Detailing Dependencies

### PR DESCRIPTION
**Pull request by cstns**
## Description

Implemented Design: Draft 1 from parent issue

## Related Issue(s)

closes https://github.com/FlowFuse/flowfuse/issues/4363

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Rubber ducked with Steve - it's because I was running a local stack with my Dashboard development environment setup. Anything installed via FlowFuse > Settings > Palette, or the Palette Manager works great.

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Awaiting final tests to pass, but this is great

**Comment by joepavitt** [comment]
@cstns please make sure we get a changelog entry for this please, and follow up with the #4501 for documentation

**Comment by cstns** [comment]
Created https://github.com/FlowFuse/website/issues/2565 for the changelog entry, will tackle both changelog & docs first thing tomorrow

**Pull request merged**
