### PR TITLE
DevOps Pipelines: Deploy active device snapshot

### LINKED ISSUE #3113: Deploy currently active snapshot from a device
### Description

Today, devices can only deploy their _own snapshots_ along the pipeline.

However, a device can run a snapshot from another instance or device.

An option to use the currently active snapshot during deploy should be added.

### Epic/Story

Follow up to #2756

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

**Do not merge**: This is likely to be part of a follow up release.

Adds support to DevOps pipelines for a device to deploy its currently active snapshot (which might not be from this device) to the next stage in the pipeline. Rather than requiring the user to manually create a snapshot for the device.

This is much clearer to the user, and likely to be the most frequently used, given a device must be in developer mode to create a snapshot which can then deploy.

Screenshot 2023-11-23 at 11 26 29
Screenshot 2023-11-23 at 11 26 21

Feature white-boarded with @robmarcer, @joepavitt and @Steve-Mcl during a validation call this morning where Rob accidentally deployed the wrong snapshot from a device.

## Related Issue(s)

Fixes #3113 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Making some minor changes to the help text & styling to make it easier to read:

Screenshot 2023-11-23 at 10 54 19

**Comment by joepavitt** [comment]
Have also changed "Use Active Device Snapshot" > "Use Active Snapshot", just to differentiate from the "Use Latest Device Snapshot" a little more.

**Comment by joepavitt** [comment]
I am currently unable to get this working correctly. With this pipeline:

Screenshot 2023-11-23 at 11 00 06

The 3rd stage gets stuck in an infinite install loop:

Screenshot 2023-11-23 at 11 00 31

**Comment by joepavitt** [comment]
Upon refresh, I see my Device status as crashed, so I'm guessing it was unable to get the latest "Active" Snapshot. Annoyingly though, the Stage did not update to reflect this Device Status without the refresh

**Comment by joepavitt** [comment]
I am now unable to deploy anything to my device, very unhappy local setup

**Comment by joepavitt** [comment]
Deleted my pipeline, created a new one, and it immediately think it's in a pushing/running state (I haven't run the stage yet) - something is very broken on my local now

**Comment by Pezmc** [comment]
> Deleted my pipeline, created a new one, and it immediately think it's in a pushing/running state (I haven't run the stage yet) - something is very broken on my local now

This is expected behaviour, the device is not on the latest snapshot

**Review by knolleary — APPROVED** [review]

**Pull request merged**
