### PR TITLE
Remove mixed used of callback and async in fastify plugins

### LINKED ISSUE #359: Can't navigate away from "Admin > Teams"
### Current Behavior

When clicking on the "Teams" tab in the Admin panel, navigation then breaks, until I refresh the page. No errors in console.

### Expected Behavior

I should be able to continue to navigate to any of the other tabs or pages, even when viewing the "Teams" tab.

### Steps To Reproduce

"Admin Settings" > "Teams" - then behaviour occurs 100% of the time for me. Do also notice that no teams are listed.

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16.3.2
- Platform/OS: Mac
- Browser: Chrome

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

- Upgrade fastify and plugin
- Remove mix of async and callback for all fastify plugins
- Further removal of mix of async and callback

## Related Issue(s)

Fixes #359

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass - n/a
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
The MFA setup dialog is missing the qrcode:

image


The PUT to `http://localhost:3000/api/v1/user/mfa` is returning the default app page, not the expected response.

**Comment by knolleary** [comment]
Looking at the unit tests, we don't have sufficient coverage of the `/api/v1/user/mfa` routes to have caught this.

**Comment by Pezmc** [comment]
@knolleary Are you sure you have pulled the latest? I fixed that in 09ac079

**Comment by knolleary** [comment]
@Pezmc you're right - I missed that. All looks good.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
