### PR TITLE
fix: allow mixed-case usernames in backend validation

### PR DESCRIPTION
**Pull request by hardillb**
## Description

Backend username validation enforces lowercase only, front end is case insensitive, but the error message if tripped is for lowercase only.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
We currently have 1831 users with mixed-case usernames - it is something we have always allowed. Rather than stop allowing it we should update the backend validation added in #3514 to allow for it.

**Review by knolleary — CHANGES_REQUESTED** [review]
As per previous comment - rather than block this in the UI, we should update the backend validation to allow mixed case usernames.

**Review by knolleary — APPROVED** [review]

**Comment by knolleary** [comment]
I've just thrown in a couple tests for mixed-case usernames.

**Comment by hardillb** [comment]
Tests have passed, merging

**Pull request merged**
